spring:
  application:
    name: 读写分离
  datasource:
    # ReplicationDriver 规定url中第一个主机是master主机地址，剩下的全部是slave主机。另外有两个参数autoReconnect和roundRobinLoadBalance必须指定为true
    url: jdbc:mysql:replication://localhost:3306,localhost:3307,localhost:3308/test1?useUnicode=true&characterEncoding=utf8&autoReconnect=true&roundRobinLoadBalance=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.ReplicationDriver
logging:
  path: d:/logs
  level:
    com.gtw.split.mapper: debug # sql打印